CREATE TABLE Plane
(
Plane_Id INTEGER NOT NULL PRIMARY KEY UNIQUE,
Board_Number INTEGER NOT NULL,
Register_Sign VARCHAR(150) NOT NULL,
Type_Of_Plane VARCHAR(150) NOT NULL,
Year_Create DATE NOT NULL,
Lifting INTEGER NOT NULL
);