CREATE TABLE Ticket
(
Ticket_Id INTEGER NOT NULL PRIMARY KEY UNIQUE,
Place INTEGER NOT NULL,
Price DECIMAL(15,2) NOT NULL,
Passenger_Id INTEGER NOT NULL,
Airline_Id INTEGER NOT NULL,
Palne_Id INTEGER NOT NULL,
CONSTRAINT FOREIGN KEY (Passenger_Id) REFERENCES passenger (Passenger_Id) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FOREIGN KEY (Airline_Id) REFERENCES airline (Airline_Id) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FOREIGN KEY (Palne_Id) REFERENCES plane (Plane_Id) ON DELETE CASCADE ON UPDATE CASCADE
);